library/Book/urls.py
from django.urls import path

from . import views
app_name = 'book'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_book, name='add_book')
]

library/Reader/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.collect_user_info, name='index'),

]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('Reader.urls')),
    path('books/', include('Book.urls', namespace='Book'))
]

library/Book/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField()

library/Reader/models.py
from django.db import models


class Reader(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

library/Book/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'description']

library/Reader/forms.py
from django import forms

class UserForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=100)
    last_name = forms.CharField(label='Last Name', max_length=100)
    email = forms.EmailField(label='Email')

library/Book/views.py
from django.shortcuts import render, redirect
from .models import Book
from .forms import BookForm


def index(request):
    books = Book.objects.all()
    return render(request, 'book.html', {'books': books})


def add_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = BookForm()
    return render(request, 'add_book.html', {'form': form})

library/Reader/views.py
from django.shortcuts import render, redirect
from .models import Reader
from .forms import UserForm
from django.urls import reverse
from django.db import IntegrityError


def collect_user_info(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            try:
                Reader.objects.create(firstname=first_name, lastname=last_name, email=email)
                return redirect(reverse('Book:index'))
            except IntegrityError:
                error_message = "This email address is already registered."
                form.add_error('email', error_message)
    else:
        form = UserForm()
    return render(request, 'collect_user_info.html', {'form': form})

library/templates/add_book.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Book</button>
</form>

library/templates/book.html
<style>
    .search-container {
        margin-bottom: 20px;
    }

    .search-container input[type=text] {
        padding: 10px;
        border-radius: 5px;
        width: calc(100% - 20px);
        font-size: 16px;
    }

    .book-container {
        border: 1px solid #ccc;
        margin-bottom: 10px;
        padding: 10px;
    }

    .highlight {
        background-color: yellow;
    }

    .add-book-link {
        color: #ffffff;
        background-color: #007bff;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
    }

    .add-book-link:hover {
        background-color: #0056b3;
    }

</style>

<div class="search-container">
    <input type="text" name="search" id="search" autocomplete="off" placeholder="Search..."
           oninput="searchBooks()">
</div>

{%if books%}
<h1>Book List</h1>
<div id="book-list">
    {% for book in books %}
    <div class="book-container">
        <h2 class="title">{{ book.title }}</h2>
        <p class="author">Author: {{ book.author }}</p>
        <p class="description">Desc: {{ book.description }}</p>
    </div>
    {% endfor %}
</div>
{%else%}
<h1>No Books in Library. Add new one</h1>
<a class="add-book-link" href="{% url 'Book:add_book'%}">Add Book</a>
{%endif%}

<script>
    function searchBooks() {
        let input = document.getElementById('search').value.toLowerCase();
        let bookContainers = document.querySelectorAll('.book-container');

        bookContainers.forEach(container => {
            let title = container.querySelector('.title').textContent.toLowerCase();
            let author = container.querySelector('.author').textContent.toLowerCase();
            let description = container.querySelector('.description').textContent.toLowerCase();

            if (title.includes(input) || author.includes(input) || description.includes(input)) {
                container.style.display = 'block';


                if (title.includes(input)) {

                    container.querySelector('.title').innerHTML = title.replace(new RegExp(input, 'gi'), match => `<span class="highlight">${match}</span>`);
                }
                if (author.includes(input)) {

                    container.querySelector('.author').innerHTML = author.replace(new RegExp(input, 'gi'), match => `<span class="highlight">${match}</span>`);
                }
                if (description.includes(input)) {

                    container.querySelector('.description').innerHTML = description.replace(new RegExp(input, 'gi'), match => `<span class="highlight">${match}</span>`);
                }
            } else {
                container.style.display = 'none';
            }
        });


        if (input === "") {
            bookContainers.forEach(container => {
                container.style.display = 'block';
            });
        }
    }
</script>

library/templates/collect_user_info.html
<form method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit">Submit</button>
</form>